# Change these first
owner: geshii # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: based.social (Mastodon)
    url: https://based.social
    icon: https://based.social/favicon.ico
  - name: Miruku (Misskey)
    url: https://miruku.cafe
    icon: https://miruku.cafe/favicon.ico
    assignees:
      - infi
      - geshii
      - wait-what
      - insertish
  - name: Miruku Radio
    url: https://radio.miruku.cafe
    icon: https://radio.miruku.cafe/favicon.ico
  - name: Data01 (S3)
    url: $DATA_01
    icon: https://cdn-icons-png.flaticon.com/512/1925/1925155.png
  - name: NyaSafe (Storage)
    url: $VPN
    icon: http://files.geshii.moe/favicon.ico
  - name: OwnCast
    url: $VPN
    icon: http://nyan.initmd.xyz/favicon.ico
  - name: Invidious
    url:  https://yt.miruku.cafe/
    icon: https://yt.miruku.cafe/favicon.ico
  - name: VPN Server
    url: $VPN
    icon: https://cdn-icons-png.flaticon.com/512/1925/1925155.png
  - name: Mailserver
    check: "tcp-ping"
    url: vps.srv.janderedev.xyz
    port: 25
    icon: https://mail.amogus.cloud/img/cow_mailcow.svg
  - name: PSO2 Map Viewer
    url: $VPN
    icon: http://map.geshii.moe/favicon.ico
  
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.miruku.cafe
  theme: light
  links:
    - rel: stylesheet
      href: https://raw.githubusercontent.com/koishiionline/status/master/custom/style.css
  name: Status
  introTitle: "**Status page for** miruku.cafe, koishii and based.social; an org hosting multiple communication, and other services for free, such as mastodon, and more."
  introMessage: This page is updated **real-time**, and contains the current status for all the services, and more
  navbar:
    - title: Home
      href: https://koishii.online
    - title: Misskey
      href: https://miruku.cafe
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Mastodon
      href: https://based.social
    - title: Discord
      href: https://discord.gg/xp9265sPdJ

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
