# Change these first
owner: geshii # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: based.social
    url: https://based.social
    icon: https://based.social/favicon.ico
    assignees:
      - insertish
      - infi
      - geshii
      - janderedev
  - name: PSO2 Map Viewer
    url: http://map.geshii.moe
    icon: http://map.geshii.moe/favicon.ico
  - name: Chibisafe (temp instance)
    url: http://files.geshii.moe
    icon: http://files.geshii.moe/favicon.ico
  - name: Test Broken Site
    url: https://thissitedoesnotexist.koj.co

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.miruku.cafe
  theme: night
  baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/geshii/status/gh-pages/logo-192.png
  name: BasedORG Status
  introTitle: "**based.social** is an org hosting multiple services for free, such as mastodon, and more."
  introMessage: This page is updated **real-time**, and contains the current status for all the services, and more
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Mastodon
      href: https://based.social
    - title: Discord
      href: https://discord.gg/xp9265sPdJ

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
